######################################################################
##
## Filename: Counter.udo
## Created on: Wed Aug 10 8:26:13 PM Egypt Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
