######################################################################
##
## Filename: clk_diff.udo
## Created on: Tue Aug 16 2:23:21 PM Egypt Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
