######################################################################
##
## Filename: Conventional_Encoder.udo
## Created on: Thu Aug 11 12:48:51 PM Egypt Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
